#! /bin/sh
GLOBIGNORE=.
echo "#! /bin/sh" > ./.clone
for subdir in *; do
  test -d "$subdir" || continue
  cd "$subdir"
  remote=$(git remote -v)
  for word in $remote; do
    if [ `echo "$word" | grep 'git@' ` ]; then
      echo "git clone $word" >> ../.clone
    fi
  done
  cd -
done
awk '!seen[$0]++' ./.clone > ./clone
rm ./.clone
chmod a+x ./clone