#! /bin/sh
./clean
#./.makescripts/apt-git-nightly.sh
#./.makescripts/autovala-nightly.sh
#./.makescripts/awesome-lightdm-session-nightly.sh
#./.makescripts/awesome-revelation-nightly.sh
#./.makescripts/conky-switcher-nightly.sh
#./.makescripts/debian-awesome-gnome-nightly.sh
#./.makescripts/hidblock-nightly.sh
#./.makescripts/i2pd-nightly.sh
#./.makescripts/mousepad-tab-nightly.sh
#./.makescripts/ratox-nightly.sh
#./.makescripts/svirfneblin-alarm-widget-nightly.sh
./.makescripts/svirfneblin-battery-widget-nightly.sh
./.makescripts/svirfneblin-conky-hud-nightly.sh
./.makescripts/svirfneblin-conky-starter-nightly.sh
#./.makescripts/svirfneblin-hidcontrol-widget-nightly.sh
./.makescripts/svirfneblin-network-manager-nightly.sh
./.makescripts/svirfneblin-panel-nightly.sh
#./.makescripts/svirfneblin-quake-hud-nightly.sh
./.makescripts/svirfneblin-session-nightly.sh
#./.makescripts/toxbot-nightly.sh
#./.makescripts/toxcore-nightly.sh
#./.makescripts/torbrowser-launcher-nightly.sh
#./.makescripts/tox-vapi-nightly.sh
#./.makescripts/zeronet-nightly.sh
if [ "$1" = "push" ] ; then
    ./push
fi
