'\" t
.\"     Title: awesome
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/22/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "AWESOME" "1" "09/22/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
awesome \- awesome window manager
.SH "SYNOPSIS"
.sp
\fBawesome\fR [\fB\-v\fR | \fB\-\-version\fR] [\fB\-h\fR | \fB\-\-help\fR] [\fB\-c\fR | \fB\-\-config\fR \fIFILE\fR] [\fB\-k\fR | \fB\-\-check\fR]
.SH "DESCRIPTION"
.sp
\fBawesome\fR is a window manager for X\&. It manages windows in different layouts, like floating or tiled\&. Any layout can be applied dynamically, optimizing the environment for the application in use and the task currently being performed\&.
.sp
In a tiled layout, windows are managed in a master and stacking area\&. The master area contains the windows which currently need the most attention, whereas the stacking area contains all other windows\&. In a floating layout windows can be resized and moved freely\&. Dialog windows are always managed as floating, regardless of the layout currently applied\&. The spiral and dwindle layouts are special cases of the tiled layout where the stacking area is arranged in a spiral for the former or as a rectangular fractal for the later\&.
.sp
Windows are grouped by tags in awesome\&. Each window can be tagged with one or more tags\&. Selecting certain tags displays all windows with these tags\&.
.sp
\fBawesome\fR can contain small wiboxes which can display anything you want: all available tags, the current layout, the title of the visible windows, text, etc\&.
.SH "OPTIONS"
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print version information to standard output, then exit\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print help information, then exit\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\fR \fIFILE\fR
.RS 4
Use an alternate configuration file instead of
\fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR\&.
.RE
.PP
\fB\-k\fR, \fB\-\-check\fR
.RS 4
Check configuration file syntax\&.
.RE
.PP
\fB\-a\fR, \fB\-\-no\-argb\fR
.RS 4
Don\(cqt use ARGB visuals\&.
.RE
.SH "DEFAULT MOUSE BINDINGS"
.SS "Navigation"
.PP
\fBButton1\fR on tag name
.RS 4
View tag\&.
.RE
.PP
\fBButton4\fR, \fBButton5\fR on tag name
.RS 4
Switch to previous or next tag\&.
.RE
.PP
\fBButton4\fR, \fBButton5\fR on root window
.RS 4
Switch to previous or next tag\&.
.RE
.PP
\fBButton1\fR, \fBButton3\fR, \fBButton4\fR, \fBButton5\fR on layout symbol
.RS 4
Switch to previous or next layout\&.
.RE
.SS "Layout modification"
.PP
\fBMod4 + Button1\fR on tag name
.RS 4
Tag current client with this tag only\&.
.RE
.PP
\fBMod4 + Button3\fR on tag name
.RS 4
Toggle this tag for client\&.
.RE
.PP
\fBButton3\fR on tag name
.RS 4
Add this tag to current view\&.
.RE
.PP
\fBMod4 + Button1\fR on client window
.RS 4
Move window\&.
.RE
.PP
\fBMod4 + Button3\fR on client window
.RS 4
Resize window\&.
.RE
.SH "DEFAULT KEY BINDINGS"
.SS "Window manager control"
.PP
\fBMod4 + Control + r\fR
.RS 4
Restart
\fBawesome\fR\&.
.RE
.PP
\fBMod4 + Shift + q\fR
.RS 4
Quit
\fBawesome\fR\&.
.RE
.PP
\fBMod4 + r\fR
.RS 4
Run prompt\&.
.RE
.PP
\fBMod4 + x\fR
.RS 4
Run Lua code prompt\&.
.RE
.PP
\fBMod4 + Return\fR
.RS 4
Spawn terminal emulator\&.
.RE
.PP
\fBMod4 + w\fR
.RS 4
Open main menu\&.
.RE
.SS "Clients"
.PP
\fBMod4 + m\fR
.RS 4
Maximize client\&.
.RE
.PP
\fBMod4 + n\fR
.RS 4
Minimize client\&.
.RE
.PP
\fBMod4 + Control + n\fR
.RS 4
Restore client\&.
.RE
.PP
\fBMod4 + f\fR
.RS 4
Set client fullscreen\&.
.RE
.PP
\fBMod4 + Shift + c\fR
.RS 4
Kill focused client\&.
.RE
.PP
\fBMod4 + t\fR
.RS 4
Set client on\-top\&.
.RE
.SS "Navigation"
.PP
\fBMod4 + j\fR
.RS 4
Focus next client\&.
.RE
.PP
\fBMod4 + k\fR
.RS 4
Focus previous client\&.
.RE
.PP
\fBMod4 + u\fR
.RS 4
Focus first urgent client\&.
.RE
.PP
\fBMod4 + Left\fR
.RS 4
View previous tag\&.
.RE
.PP
\fBMod4 + Right\fR
.RS 4
View next tag\&.
.RE
.PP
\fBMod4 + 1\-9\fR
.RS 4
Switch to tag 1\-9\&.
.RE
.PP
\fBMod4 + Control + j\fR
.RS 4
Focus next screen\&.
.RE
.PP
\fBMod4 + Control + k\fR
.RS 4
Focus previous screen\&.
.RE
.PP
\fBMod4 + Escape\fR
.RS 4
Focus previously selected tag set\&.
.RE
.SS "Layout modification"
.PP
\fBMod4 + Shift + j\fR
.RS 4
Switch client with next client\&.
.RE
.PP
\fBMod4 + Shift + k\fR
.RS 4
Switch client with previous client\&.
.RE
.PP
\fBMod4 + o\fR
.RS 4
Send client to next screen\&.
.RE
.PP
\fBMod4 + h\fR
.RS 4
Decrease master width factor by 5%\&.
.RE
.PP
\fBMod4 + l\fR
.RS 4
Increase master width factor by 5%\&.
.RE
.PP
\fBMod4 + Shift + h\fR
.RS 4
Increase number of master windows by 1\&.
.RE
.PP
\fBMod4 + Shift + l\fR
.RS 4
Decrease number of master windows by 1\&.
.RE
.PP
\fBMod4 + Control + h\fR
.RS 4
Increase number of columns for non\-master windows by 1\&.
.RE
.PP
\fBMod4 + Control + l\fR
.RS 4
Decrease number of columns for non\-master windows by 1\&.
.RE
.PP
\fBMod4 + space\fR
.RS 4
Switch to next layout\&.
.RE
.PP
\fBMod4 + Shift + space\fR
.RS 4
Switch to previous layout\&.
.RE
.PP
\fBMod4 + Control + space\fR
.RS 4
Toggle client floating status\&.
.RE
.PP
\fBMod4 + Control + Return\fR
.RS 4
Swap focused client with master\&.
.RE
.PP
\fBMod4 + Control + 1\-9\fR
.RS 4
Toggle tag view\&.
.RE
.PP
\fBMod4 + Shift + 1\-9\fR
.RS 4
Tag client with tag\&.
.RE
.PP
\fBMod4 + Shift + Control + 1\-9\fR
.RS 4
Toggle tag on client\&.
.RE
.SH "CUSTOMIZATION"
.sp
\fBawesome\fR is customized by creating a custom \fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR file\&.
.SH "SIGNALS"
.sp
\fBawesome\fR can be restarted by sending it a SIGHUP\&.
.SH "SEE ALSO"
.sp
\fBawesomerc\fR(5) \fBawesome\-client\fR(1)
.SH "BUGS"
.sp
Of course there\(cqs no bug in \fBawesome\fR\&. But there may be unexpected behaviors\&.
.SH "AUTHORS"
.sp
Julien Danjou <\m[blue]\fBjulien@danjou\&.info\fR\m[]\&\s-2\u[1]\d\s+2> and others\&.
.SH "WWW"
.sp
\m[blue]\fBhttp://awesome\&.naquadah\&.org\fR\m[]
.SH "NOTES"
.IP " 1." 4
julien@danjou.info
.RS 4
\%mailto:julien@danjou.info
.RE
