'\" t
.\"     Title: awesome
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/22/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "AWESOME" "1" "09/22/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
awesome \- gestor de ventanas awesome
.SH "SINOPSIS"
.sp
\fBawesome\fR [\fB\-v\fR | \fB\-\-version\fR] [\fB\-h\fR | \fB\-\-help\fR] [\fB\-c\fR | \fB\-\-config\fR \fIFICHERO\fR] [\fB\-k\fR | \fB\-\-check\fR]
.SH "DESCRIPCI\('ON"
.sp
\fBawesome\fR es un gestor de ventanas para el sistema de ventanas X\&. Organiza las ventanas utilizando diferentes disposiciones o esquemas (layouts), como por ejemplo superpuestas o en mosaico\&. Cualquiera de los esquemas puede ser aplicado din\('amicamente, optimizando el entorno para la aplicaci\('on que se est\('e ejecutando o la tarea que se est\('e llevando a cabo\&.
.sp
En los esquemas en mosaico la pantalla se divide en un \('area principal y un \('area de apilamiento\&. El \('area principal contiene las ventanas que necesitan mayor cantidad de atenci\('on, mientras que el \('area de apilamiento contiene el resto de ventanas\&. En los esquemas flotantes las ventanas pueden ser desplazadas y redimensionadas por el usuario sin restricciones\&. Las ventanas de di\('alogo siempre se consideran flotantes, independientemente del esquema que est\('e aplicado en ese momento\&. El esquema en espiral y el menguante son casos particulares de los esquemas en mosaico, en los que el \('area de apilamiento se organiza, respectivamente, en forma de espiral o dividi\('endose en rect\('angulos siguiendo un patr\('on fractal\&.
.sp
Las ventanas se agrupan por etiquetas en awesome\&. Cada ventana puede tener una o m\('as etiquetas\&. Al seleccionar una etiqueta se muestran todas las ventanas que tienen esa etiqueta\&.
.sp
En \fBawesome\fR se pueden a\(~nadir wiboxes que pueden mostrar cualquier valor: todas las etiquetas existentes, el esquema que est\('a seleccionado, el t\('itulo de las ventanas visibles, texto, etc\&.
.SH "OPCIONES"
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Muestra la informaci\('on de la versi\('on en la salida est\('andar, y sale del programa\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Muestra informaci\('on de ayuda, y sale del programa\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\fR \fIFICHERO\fR
.RS 4
Utiliza un fichero de configuraci\('on alternativo en lugar de
\fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR\&.
.RE
.PP
\fB\-k\fR, \fB\-\-check\fR
.RS 4
Verifica la sintaxis del archivo de configuraci\('on\&.
.RE
.PP
\fB\-a\fR, \fB\-\-no\-argb\fR
.RS 4
No utilice colores ARGB\&.
.RE
.SH "ATAJOS DE RAT\('ON POR OMISI\('ON"
.SS "Navegaci\('on"
.PP
\fBBot\('on1\fR en el nombre de una etiqueta
.RS 4
Muestra las ventanas con esa etiqueta\&.
.RE
.PP
\fBBot\('on4\fR, \fBBot\('on5\fR en el nombre de una etiqueta
.RS 4
Cambia a la etiqueta anterior o siguiente\&.
.RE
.PP
\fBBot\('on4\fR, \fBBot\('on5\fR en la ventana de fondo
.RS 4
Cambia a la etiqueta anterior o siguiente\&.
.RE
.PP
\fBButton1\fR, \fBButton3\fR, \fBButton4\fR, \fBButton5\fR en el s\('imbolo de esquema
.RS 4
Cambia al esquema anterior o siguiente\&.
.RE
.SS "Modificaci\('on del esquema"
.PP
\fBMod4 + Bot\('on1\fR en el nombre de una etiqueta
.RS 4
Etiqueta al cliente actual \('unicamente con esa etiqueta\&.
.RE
.PP
\fBMod4 + Bot\('on\fR en el nombre de una etiqueta
.RS 4
Activa o desactiva esa etiqueta para el cliente actual\&.
.RE
.PP
\fBBot\('on3\fR en el nombre de una etiqueta
.RS 4
A\(~nade el contenido de esa etiqueta a la vista actual\&.
.RE
.PP
\fBMod4 + Bot\('on1\fR en una ventana cliente
.RS 4
Mueve la ventana\&.
.RE
.PP
\fBMod4 + Bot\('on3\fR en una ventana cliente
.RS 4
Redimensiona la ventana\&.
.RE
.SH "ATAJOS DE TECLADO POR OMISI\('ON"
.SS "Control del gestor de ventanas"
.PP
\fBMod4 + Control + r\fR
.RS 4
Reinicia
\fBawesome\fR\&.
.RE
.PP
\fBMod4 + May\('us + q\fR
.RS 4
Sale de
\fBawesome\fR\&.
.RE
.PP
\fBMod4 + r\fR
.RS 4
Ejecuta una l\('inea de comandos en la barra de estado\&.
.RE
.PP
\fBMod4 + x\fR
.RS 4
Ejecuta una l\('inea de comandos de Lua en la barra de estado\&.
.RE
.PP
\fBMod4 + Intro\fR
.RS 4
Lanza una instancia del emulador de terminal\&.
.RE
.PP
\fBMod4 + w\fR
.RS 4
Despliega el men\('u principal\&.
.RE
.SS "Clientes"
.PP
\fBMod4 + m\fR
.RS 4
Maximiza el cliente actual\&.
.RE
.PP
\fBMod4 + n\fR
.RS 4
Minimiza el cliente actual\&.
.RE
.PP
\fBMod4 + Control + n\fR
.RS 4
Restaurar el cliente\&.
.RE
.PP
\fBMod4 + f\fR
.RS 4
Activa o desactiva el modo de pantalla completa para el cliente actual\&.
.RE
.PP
\fBMod4 + May\('us + c\fR
.RS 4
Termina (kill) el cliente actual\&.
.RE
.PP
\fBMod4 + t\fR
.RS 4
Activa o desactiva el modo "siempre visible" para el cliente actual\&.
.RE
.SS "Navegaci\('on"
.PP
\fBMod4 + j\fR
.RS 4
Establece el foco sobre el cliente siguiente\&.
.RE
.PP
\fBMod4 + k\fR
.RS 4
Establece el foco sobre el cliente anterior\&.
.RE
.PP
\fBMod4 + u\fR
.RS 4
Establece el foco sobre el primer cliente urgente\&.
.RE
.PP
\fBMod4 + Left\fR
.RS 4
Muestra la etiqueta anterior\&.
.RE
.PP
\fBMod4 + Right\fR
.RS 4
Muestra la etiqueta siguiente\&.
.RE
.PP
\fBMod4 + 1\-9\fR
.RS 4
Muestra los contenidos de la etiqueta 1\-9\&.
.RE
.PP
\fBMod4 + Control + j\fR
.RS 4
Establece el foco en la pantalla siguiente\&.
.RE
.PP
\fBMod4 + Control + k\fR
.RS 4
Establece el foco en la pantalla anterior\&.
.RE
.PP
\fBMod4 + Escape\fR
.RS 4
Establece el foco en el conjunto de etiquetas seleccionado anteriormente\&.
.RE
.SS "Modificaci\('on del esquema"
.PP
\fBMod4 + May\('us + j\fR
.RS 4
Intercambia el cliente actual con el cliente siguiente\&.
.RE
.PP
\fBMod4 + May\('us + k\fR
.RS 4
Intercambia el cliente actual con el cliente anterior\&.
.RE
.PP
\fBMod4 + o\fR
.RS 4
Env\('ia el cliente a la pantalla siguiente\&.
.RE
.PP
\fBMod4 + h\fR
.RS 4
Decrementa la anchura del \('area principal en un 5%\&.
.RE
.PP
\fBMod4 + l\fR
.RS 4
Incrementa la anchura del \('area principal en un 5%\&.
.RE
.PP
\fBMod4 + May\('us + h\fR
.RS 4
Incrementa el n\('umero de ventanas en el \('area principal en 1\&.
.RE
.PP
\fBMod4 + May\('us + l\fR
.RS 4
Decrementa el n\('umero de ventanas en el \('area principal en 1\&.
.RE
.PP
\fBMod4 + Control + h\fR
.RS 4
Incrementa el n\('umero de columnas en el \('area de apilamiento en 1\&.
.RE
.PP
\fBMod4 + Control + l\fR
.RS 4
Decrementa el n\('umero de columnas en el \('area de apilamiento en 1\&.
.RE
.PP
\fBMod4 + space\fR
.RS 4
Cambia al esquema siguiente\&.
.RE
.PP
\fBMod4 + May\('us + espacio\fR
.RS 4
Cambia al esquema anterior\&.
.RE
.PP
\fBMod4 + Control + espacio\fR
.RS 4
Activa o desactiva el estado flotante del cliente actual
.RE
.PP
\fBMod4 + Control + Intro\fR
.RS 4
Intercambia el cliente actual con el cliente en el \('area principal
.RE
.PP
\fBMod4 + Control + 1\-9\fR
.RS 4
Activa o desactiva la vista de la etiqueta 1\-9\&.
.RE
.PP
\fBMod4 + May\('us + 1\-9\fR
.RS 4
Etiqueta al cliente actual con la etiqueta 1\-9\&.
.RE
.PP
\fBMod4 + May\('us + Control + 1\-9\fR
.RS 4
Activa o desactiva la etiqueta 1\-9 para el cliente actual\&.
.RE
.SH "PERSONALIZACI\('ON"
.sp
\fBawesome\fR se configura creando un fichero \fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR personalizado\&.
.SH "SE\(~NALES"
.sp
La se\(~nal SIGHUP provoca que \fBawesome\fR se reinicie\&.
.SH "V\('EASE TAMBI\('EN"
.sp
\fBawesomerc\fR(5) \fBawesome\-client\fR(1)
.SH "FALLOS"
.sp
Por supuesto, \fBawesome\fR no tiene fallos\&. Pero es posible que tenga comportamientos inesperados\&.
.SH "AUTORES"
.sp
Julien Danjou <\m[blue]\fBjulien@danjou\&.info\fR\m[]\&\s-2\u[1]\d\s+2> y otros\&.
.SH "WWW"
.sp
\m[blue]\fBhttp://awesome\&.naquadah\&.org\fR\m[]
.SH "TRADUCCI\('ON"
.sp
Esta p\('agina de manual ha sido traducida por Diego Moreda\&.
.SH "NOTES"
.IP " 1." 4
julien@danjou.info
.RS 4
\%mailto:julien@danjou.info
.RE
