'\" t
.\"     Title: awesomerc
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/22/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "AWESOMERC" "5" "09/22/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
awesomerc \- Konfigurationsdatei f\(:ur den awesome Fenstermanager
.SH "SYNTAX"
.sp
\fBawesome\fR sucht nach einer Konfigurationsdatei in der folgenden Reihenfolge:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
$XDG_CONFIG_HOME/awesome/rc\&.lua
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
$HOME/\&.config/awesome/rc\&.lua
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
XDG_CONFIG_DIRS/awesome/rc\&.lua
.RE
.SH "BESCHREIBUNG"
.sp
Die \fBrc\&.lua\fR Datei beinhaltet Konfigurationen f\(:ur \fBawesome\fR\&. Sie kann benutzt werden um das Verhalten und das Aussehen von awesome auf verschiedene Weise zu beeinflussen\&. Die Konfigurationsdatei kann als Lua\-Programm verstanden werden, welches beim Start von \fBawesome\fR ausgef\(:uhrt wird\&. Hierf\(:ur sollte sie die awesome LUA API benutzen, welche im Abschnitt API vorgestellt wird\&.
.SH "AWESOME LUA API"
.sp
Dokumentationen f\(:ur die Lua API befinden sich im Verzeichnis luadoc\&.
.SH "FARBFORMATIERUNG"
.sp
Die Farbformate in \fBawesome\fR sind entweder die Standard X Farbnamen (blue, darkblue, lightred, etc) oder eine Hexadezimaldarstellung der Farbe (#rrggbb oder #rrggbbaa)\&. Bei der Nutzung der Hexadezimaldarstellung kann zudem ein Alpha\-Kanal genutzt werden\&. Dies bedeutet, dass #00ff00 gr\(:un zeichnen wird, aber #00ff00aa setzt den Alpha\-Kanal auf \(oqaa\(cq und l\(:asst somit die darunter liegende Farbe durch den gr\(:unen Teil durchschimmern\&.
.SH "TEXTFORMATERUNG"
.sp
Sie k\(:onnen Pango\-Markups in Texten benutzen\&. Dies erlaubt die Formatierung von Texten, welche in einem Widget dargestellt werden\&. Die Pango\-Markup Dokumentation k\(:onnen sie in der Dokumentation zu Pango unter \m[blue]\fBhttp://library\&.gnome\&.org/devel/pango/stable/PangoMarkupFormat\&.html\fR\m[] nachlesen\&.
.sp
Ein Pango\-Markup Beispiel: <span weight="bold" foreground="#336699">\&...</span>\&.
.SH "SIEHE AUCH"
.sp
awesome(1) awesome\-client(1)
.SH "AUTOREN"
.sp
Geschrieben von Julien Danjou <\m[blue]\fBjulien@danjou\&.info\fR\m[]\&\s-2\u[1]\d\s+2>\&.
.SH "WWW"
.sp
\m[blue]\fBhttp://awesome\&.naquadah\&.org\fR\m[]
.SH "NOTES"
.IP " 1." 4
julien@danjou.info
.RS 4
\%mailto:julien@danjou.info
.RE
