'\" t
.\"     Title: awesome-client
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/22/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "AWESOME\-CLIENT" "1" "09/22/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
awesome-client \- esecutore remoto per il gestore di finestre awesome
.SH "SINOSSI"
.sp
awesome\-client
.SH "DESCRIZIONE"
.sp
awesome\-client \(`e un\(cqinterfaccia a riga di comando per awesome\&. Comunica con awesome via D\-Bus, consentendo l\(cqesecuzione remota di codice Lua\&.
.SH "UTILIZZO"
.sp
awesome\-client riceve comandi dall\(cqingresso standard e li invia via D\-Bus ad awesome\&. Se \fIrlwrap\fR \(`e installato, sar\(`a utilizzato per fornire un\(cqinterfaccia da riga di comando per le funzionalit\(`a di readline\&.
.sp
Il modulo \fIawful\&.remote\fR deve essere caricato per far funzionare questo comando\&.
.SH "VEDI ANCHE"
.sp
awesome(1) awesomerc(5)
.SH "AUTORI"
.sp
Julien Danjou <\m[blue]\fBjulien@danjou\&.info\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "WWW"
.sp
\m[blue]\fBhttp://awesome\&.naquadah\&.org\fR\m[]
.SH "TRADUZIONE"
.sp
Questa pagina di manuale \(`e stata tradotta da Gianluca Fiore\&.
.SH "NOTES"
.IP " 1." 4
julien@danjou.info
.RS 4
\%mailto:julien@danjou.info
.RE
