'\" t
.\"     Title: awesome
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/22/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "AWESOME" "1" "09/22/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
awesome \- awesome Fenstermanager
.SH "SYNTAX"
.sp
\fBawesome\fR [\fB\-v\fR | \fB\-\-version\fR] [\fB\-h\fR | \fB\-\-help\fR] [\fB\-c\fR | \fB\-\-config\fR \fIDatei\fR] [\fB\-k\fR | \fB\-\-check\fR]
.SH "BESCHREIBUNG"
.sp
\fBawesome\fR ist ein Fenstermanager f\(:ur X\&. Er verwaltet Fenster in verschiedenen Anordnungen, wie etwa \(:uberlappend oder geteilt\&. Jede Anordnung kann dynamisch angewendet werden, wodurch eine optimale Anpassung an die aktuelle Anwendung und die entsprechende T\(:atigkeit vorgenommen werden kann\&.
.sp
In einer geteilten Anordnung werden Fenster in einer Haupt\- und einer Stackanordnung abgebildet\&. Das Hauptfenster ist das Fenster, welches die meiste Aufmerksamkeit ben\(:otigt, hingegen beinhaltet der Stack alle weiteren Fenster\&. In einer \(:uberlappenden Anordnung k\(:onnen Fenster beliebig vergr\(:o\(ssert und verschoben werden\&. Dialog\-Fenster werden immer als \(:uberlappend behandelt, unabh\(:angig von der aktuellen Anordnung\&. Die spiralf\(:ormige und die vermindernde Anordnung sind Spezialf\(:alle der geteilten Anordnung, wobei die Stack\-Fl\(:ache als Spirale f\(:ur die obersten oder als rechteckiges Fraktal f\(:ur die untersten dient\&.
.sp
Fenster sind durch Bezeichner (Tags) in awesome gruppiert\&. Jedes Fenster kann mit einem oder mehreren Bezeichnern versehen werden\&. Bei der Auswahl eines Bezeichners werden dabei alle Fenster angezeigt, die mit diesem Bezeichner markiert wurden\&.
.sp
\fBawesome\fR kann kleine Wiboxes beinhalten, welche zur Anzeige von beliebigen Inhalt dienen k\(:onnen, wie etwa: Alle verf\(:ugbaren Bezeichner, die aktuelle Anordnung, der Titel eines sichtbaren Fenster, Text, etc\&.
.SH "OPTIONEN"
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Gibt die Versionsinformationen auf der Standard\-Ausgabe aus\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Gibt die Hilfe aus\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\fR \fIDatei\fR
.RS 4
Nutzung einer alternativen Konfigurationsdatei, statt
\fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR\&.
.RE
.PP
\fB\-k\fR, \fB\-\-check\fR
.RS 4
\(:Uberpr\(:uft die Konfigurationsdatei auf Syntaxfehler\&.
.RE
.PP
\fB\-a\fR, \fB\-\-no\-argb\fR
.RS 4
Verwende keine ARGB\-Visuals
.RE
.SH "TASTENBELEGUNG F\(:UR MAUSZEIGER"
.SS "Navigation"
.PP
\fBButton1\fR auf Bezeichner
.RS 4
Bezeichner anzeigen\&.
.RE
.PP
\fBButton4\fR, \fBButton5\fR auf Bezeichner
.RS 4
Wechsel zum vorhergehenden oder n\(:achsten Bezeichner\&.
.RE
.PP
\fBButton4\fR, \fBButton5\fR auf Root\-Fenster
.RS 4
Wechsel zum vorhergehenden oder n\(:achsten Bezeichner\&.
.RE
.PP
\fBButton1\fR, \fBButton3\fR, \fBButton4\fR, \fBButton5\fR auf Anordnungssymbol
.RS 4
Wechsel zur vorhergehenden oder n\(:achsten Anordnung\&.
.RE
.SS "Ver\(:anderung der Anordnung"
.PP
\fBMod4 + Button1\fR auf Bezeichner
.RS 4
Aktuelles Fenster nur mit diesem Bezeichner markieren\&.
.RE
.PP
\fBMod4 + Button3\fR auf Bezeichner
.RS 4
Wechsel des Bezeichners f\(:ur das aktuelle Fenster\&.
.RE
.PP
\fBButton3\fR auf Bezeichner
.RS 4
Bezeichner in die aktuelle Ansicht mit aufnehmen\&.
.RE
.PP
\fBMod4 + Button1\fR auf Fenster
.RS 4
Fenster bewegen\&.
.RE
.PP
\fBMod4 + Button3\fR auf Fenster
.RS 4
Fenster vergr\(:o\(ssern\&.
.RE
.SH "TASTENK\(:URZEL"
.SS "Fenstermanager kontrollieren"
.PP
\fBMod4 + Control + r\fR
.RS 4
\fBawesome\fR
neu starten\&.
.RE
.PP
\fBMod4 + Shift + q\fR
.RS 4
\fBawesome\fR
beenden\&.
.RE
.PP
\fBMod4 + r\fR
.RS 4
Eingabeaufforderung\&.
.RE
.PP
\fBMod4 + x\fR
.RS 4
Lua\-Code Eingabeaufforderung\&.
.RE
.PP
\fBMod4 + Return\fR
.RS 4
Konsolenemulator starten\&.
.RE
.PP
\fBMod4 + w\fR
.RS 4
Hauptmen\(:u \(:offnen\&.
.RE
.SS "Fenster"
.PP
\fBMod4 + m\fR
.RS 4
Fenster maximieren\&.
.RE
.PP
\fBMod4 + n\fR
.RS 4
Fenster minimieren\&.
.RE
.PP
\fBMod4 + Control + n\fR
.RS 4
Fenster wiederherstellen\&.
.RE
.PP
\fBMod4 + f\fR
.RS 4
Fenster auf Vollbild setzen\&.
.RE
.PP
\fBMod4 + Shift + c\fR
.RS 4
Aktuelles Fenster beenden\&.
.RE
.PP
\fBMod4 + t\fR
.RS 4
Fenster auf oberste Ebene setzen\&.
.RE
.SS "Navigation"
.PP
\fBMod4 + j\fR
.RS 4
Fokus auf das n\(:achste Fenster legen\&.
.RE
.PP
\fBMod4 + k\fR
.RS 4
Fokus auf das vorhergehende Fenster legen\&.
.RE
.PP
\fBMod4 + u\fR
.RS 4
Fokus auf das erste dringliche Fenster legen\&.
.RE
.PP
\fBMod4 + Left\fR
.RS 4
Anzeige des vorhergehenden Bezeichners\&.
.RE
.PP
\fBMod4 + Right\fR
.RS 4
Anzeige des n\(:achsten Bezeichners\&.
.RE
.PP
\fBMod4 + 1\-9\fR
.RS 4
Wechsel zwischen den Bezeichnern 1\-9\&.
.RE
.PP
\fBMod4 + Control + j\fR
.RS 4
Fokus auf den n\(:achsten Bildschirm legen\&.
.RE
.PP
\fBMod4 + Control + k\fR
.RS 4
Fokus auf den vorhergehenden Bildschirm legen\&.
.RE
.PP
\fBMod4 + Escape\fR
.RS 4
Fokus auf den zuvor gew\(:ahlten Bezeichner legen\&.
.RE
.SS "Anordnungs\(:anderung"
.PP
\fBMod4 + Shift + j\fR
.RS 4
Wechsel zwischen aktuellem und n\(:achstem Fenster
.RE
.PP
\fBMod4 + Shift + k\fR
.RS 4
Wechsel zwischen aktuellem und vorhergehenden Fenster\&.
.RE
.PP
\fBMod4 + o\fR
.RS 4
Verschiebe Fenster auf den n\(:achsten Bildschirm\&.
.RE
.PP
\fBMod4 + h\fR
.RS 4
Erniedrige Breite des Hauptfensters um 5%\&.
.RE
.PP
\fBMod4 + l\fR
.RS 4
Erh\(:ohe die Breite des Hauptfensters um 5%\&.
.RE
.PP
\fBMod4 + Shift + h\fR
.RS 4
Erh\(:ohe die Anzahl der Hauptfenster um 1\&.
.RE
.PP
\fBMod4 + Shift + l\fR
.RS 4
Erniedrige die Anzahl der Hauptfenster um 1\&.
.RE
.PP
\fBMod4 + Control + h\fR
.RS 4
Erh\(:ohe die Anzahl der Spalten f\(:ur Nicht\-Hauptfenster um 1\&.
.RE
.PP
\fBMod4 + Control + l\fR
.RS 4
Erniedrige die Anzahl der Spalten f\(:ur Nicht\-Hauptfenster um 1\&.
.RE
.PP
\fBMod4 + space\fR
.RS 4
Wechsel zur n\(:achsten Anordnung\&.
.RE
.PP
\fBMod4 + Shift + space\fR
.RS 4
Wechsel zur vorhergehenden Anordnung\&.
.RE
.PP
\fBMod4 + Control + space\fR
.RS 4
\(:Uberlappen aktivieren/deaktivieren\&.
.RE
.PP
\fBMod4 + Control + Return\fR
.RS 4
Wechsel des Haupt mit dem Stack\-Fenster\&.
.RE
.PP
\fBMod4 + Control + 1\-9\fR
.RS 4
Wechsel der Bezeichneransicht\&.
.RE
.PP
\fBMod4 + Shift + 1\-9\fR
.RS 4
Markiere Fenster mit Bezeichner\&.
.RE
.PP
\fBMod4 + Shift + Control + 1\-9\fR
.RS 4
Wechsel des Bezeichners des Fensters\&.
.RE
.SH "ANPASSUNG"
.sp
\fBawesome\fR kann durch die Erstellung einer \fI$XDG_CONFIG_HOME/awesome/rc\&.lua\fR Konfigurationsdatei angepasst werden\&.
.SH "SIGNALE"
.sp
\fBawesome\fR kann durch das senden eines SIGHUP neu gestartet werden\&.
.SH "SIEHE AUCH"
.sp
\fBawesomerc\fR(5) \fBawesome\-client\fR(1)
.SH "FEHLER"
.sp
Nat\(:urlich gibt es keine Fehler in \fBawesome\fR\&. Dennoch k\(:onnen unerwartete Ereignisse auftreten\&.
.SH "AUTOREN"
.sp
Julien Danjou <\m[blue]\fBjulien@danjou\&.info\fR\m[]\&\s-2\u[1]\d\s+2> und andere\&.
.SH "WWW"
.sp
\m[blue]\fBhttp://awesome\&.naquadah\&.org\fR\m[]
.SH "NOTES"
.IP " 1." 4
julien@danjou.info
.RS 4
\%mailto:julien@danjou.info
.RE
